#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

require 'pry'

@hash = {}
def fibonaci(n)
  return 0 if n == 0
  return 1 if n == 1
  return @hash[n] if @hash[n]
  @hash[n] = fibonaci(n - 1) + fibonaci(n - 2)
end

def fibonacci_interatively(n)
  sum, a, b = 0, 1, 2
  while b < n
    sum += b if b.odd?
    a, b = b, a + b
  end
  sum
end

puts fibonacci_interatively(4000000)
